# Generated by Django 5.2.6 on 2025-09-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('tipo_reactor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Reactor')),
                ('potencia_neta', models.IntegerField(blank=True, null=True, verbose_name='Potencia Neta (MWe)')),
                ('inicio_construccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inicio de Construcción')),
                ('conexion_red', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conexión a la Red')),
                ('cierre_permanente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cierre Permanente')),
                ('dueño', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dueño')),
                ('operador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Reactor',
                'verbose_name_plural': 'Reactores',
                'ordering': ['nombre'],
            },
        ),
    ]
