# Generated by Django 5.2.6 on 2025-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactor',
            name='cierre_permanente',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='conexion_red',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inicio_construccion',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='tipo_reactor',
        ),
        migrations.AddField(
            model_name='reactor',
            name='capacidad_bruta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad Bruta (MWe)'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='capacidad_termica',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad Térmica (MWt)'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='fecha_cierre_permanente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reactor',
            name='fecha_inicio_construccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reactor',
            name='fecha_primera_conexion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reactor',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='nombre_alternativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
