# Generated by Django 5.2.6 on 2025-09-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactores', '0002_remove_reactor_cierre_permanente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('electricidad_suministrada', models.FloatField(blank=True, null=True)),
                ('potencia_referencia', models.IntegerField(blank=True, null=True)),
                ('tiempo_en_linea_anual', models.FloatField(blank=True, null=True)),
                ('factor_operacion', models.FloatField(blank=True, null=True)),
                ('factor_carga_anual', models.FloatField(blank=True, null=True)),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reactores.reactor')),
            ],
            options={
                'ordering': ['ano'],
                'unique_together': {('reactor', 'ano')},
            },
        ),
    ]
