# Generated by Django 5.2.6 on 2025-09-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactores', '0003_historialrendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='tipo_reactor_categoria',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Categoría de Tipo'),
        ),
    ]
