# Generated by Django 5.2.6 on 2025-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactores', '0004_reactor_tipo_reactor_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reactor',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
